apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name}}
  labels:
    app: {{ .Values.backend.labels.app}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.service.targetPort}}
  selector:
    app: {{ .Values.backend.labels.app}}