---
- hosts: localhost
  vars:
    app_name: todo
    app_port: 3000
    compose_file: ./docker-compose.yml
  tasks:
    # - name: Install Docker
    #   apt:
    #     name: docker.io
    #     state: present
    # - name: Install Docker Compose
    #   command: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
    # - name: Copy Docker Compose file
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: "{{ compose_file }}"
    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: "."
